const actionTypes = {
  ALL_HOTELS: 'ALL_HOTELS',
  SINGLE_HOTEL: 'SINGLE_HOTEL',
  SIGN_UP: 'SIGN_UP',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
  AUTHENTICATE: 'AUTHENTICATE',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  FAVOURITES: 'FAVOURITES',
  ADD_FAVOURITES: 'ADD_FAVOURITES',
  REMOVE_FAVOURITES: 'REMOVE_FAVOURITES',
};

export default actionTypes;
