const actionTypes = {
  ALL_HOTELS: 'ALL_HOTELS',
  SINGLE_HOTEL: 'SINGLE_HOTEL',
  SIGN_UP: 'SIGN_UP',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
};

export default actionTypes;
